apiVersion: v1
kind: Service
metadata:
  name: resource-monitor-service
spec:
  selector:
    app: resource-monitor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5050
  type: NodePort
  